# -*- coding: utf-8 -*-
"""Nassau_Candy_Shipping_Route_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5Hadc-_9Zh4mlK-jdVNpfKk0aneWWVD
"""

# ============================================
# 1. IMPORT LIBRARIES
# ============================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

from IPython.display import display

print("Libraries loaded successfully!")

# ============================================
# 2. LOAD EXCEL WORKBOOK
# ============================================

file_path = "/content/Nassau Candy Distributor 1 (1).xlsx"

excel_file = pd.ExcelFile(file_path)

print("Available sheets:")
for sheet in excel_file.sheet_names:
    print("-", sheet)

# ============================================
# 3. LOAD RAW DATA
# ============================================

df = pd.read_excel(
    file_path,
    sheet_name="Raw data"
)

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

display(df.head())

# ============================================
# 5. DATASET INFORMATION
# ============================================

df.info()

# ============================================
# 6. MISSING VALUES
# ============================================

missing_values = df.isnull().sum()

missing_table = pd.DataFrame({
    "Column": missing_values.index,
    "Missing Values": missing_values.values,
    "Missing %": (missing_values.values / len(df) * 100).round(2)
})

display(
    missing_table.sort_values(
        "Missing Values",
        ascending=False
    )
)

# ============================================
# 7. DUPLICATE CHECK
# ============================================

duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

# ============================================
# 8. DATE CONVERSION
# ============================================

df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    errors="coerce"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    errors="coerce"
)

print("Order Date range:")
print(df["Order Date"].min(), "to", df["Order Date"].max())

print("\nShip Date range:")
print(df["Ship Date"].min(), "to", df["Ship Date"].max())

# ============================================
# 9. SHIPPING LEAD TIME
# ============================================

df["Shipping Lead Time"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

display(
    df["Shipping Lead Time"].describe()
)

# ============================================
# 10. DATA QUALITY STATUS
# ============================================

def check_date_quality(row):

    if pd.isna(row["Order Date"]):
        return "Missing Order Date"

    if pd.isna(row["Ship Date"]):
        return "Missing Ship Date"

    if row["Ship Date"] < row["Order Date"]:
        return "Invalid Date"

    if row["Shipping Lead Time"] > 365:
        return "Review Date"

    return "Valid"


df["Data Quality Status"] = df.apply(
    check_date_quality,
    axis=1
)

display(
    df["Data Quality Status"]
    .value_counts()
    .to_frame("Records")
)

# ============================================
# 11. PRODUCT TO FACTORY MAPPING
# ============================================

product_factory = {

    "Wonka Bar - Nutty Crunch Surprise":
        "Lot's O' Nuts",

    "Wonka Bar - Fudge Mallows":
        "Lot's O' Nuts",

    "Wonka Bar -Scrumdiddlyumptious":
        "Lot's O' Nuts",

    "Wonka Bar - Milk Chocolate":
        "Wicked Choccy's",

    "Wonka Bar - Triple Dazzle Caramel":
        "Wicked Choccy's",

    "Laffy Taffy":
        "Sugar Shack",

    "SweeTARTS":
        "Sugar Shack",

    "Nerds":
        "Sugar Shack",

    "Fun Dip":
        "Sugar Shack",

    "Fizzy Lifting Drinks":
        "Sugar Shack",

    "Everlasting Gobstopper":
        "Secret Factory",

    "Lickable Wallpaper":
        "Secret Factory",

    "Wonka Gum":
        "Secret Factory",

    "Hair Toffee":
        "The Other Factory",

    "Kazookles":
        "The Other Factory"
}

# ============================================
# 12. MAP PRODUCTS TO FACTORIES
# ============================================

df["Factory"] = df["Product Name"].map(product_factory)

print("Factory distribution:")
display(
    df["Factory"]
    .value_counts(dropna=False)
    .to_frame("Shipments")
)

# ============================================
# 13. CHECK UNMAPPED PRODUCTS
# ============================================

unmapped = df.loc[
    df["Factory"].isna(),
    "Product Name"
].unique()

print("Unmapped products:")

if len(unmapped) == 0:
    print("None - all products mapped successfully!")
else:
    for product in unmapped:
        print("-", product)

# ============================================
# 14. CREATE ROUTE
# ============================================

df["Route"] = (
    df["Factory"].astype(str)
    + " → "
    + df["State/Province"].astype(str)
)

df["Regional Route"] = (
    df["Factory"].astype(str)
    + " → "
    + df["Region"].astype(str)
)

display(
    df[
        [
            "Factory",
            "State/Province",
            "Region",
            "Route"
        ]
    ].head(10)
)

# ============================================
# 15. FEATURE ENGINEERING
# ============================================

df["Order Month"] = df["Order Date"].dt.to_period("M").astype(str)

df["Order Year"] = df["Order Date"].dt.year

df["Gross Margin %"] = np.where(
    df["Sales"] != 0,
    df["Gross Profit"] / df["Sales"] * 100,
    0
)

# Delay threshold used only as an analytical flag
DELAY_THRESHOLD = 5

df["Delay Flag"] = np.where(
    df["Shipping Lead Time"] > DELAY_THRESHOLD,
    "Delayed",
    "On Time"
)

display(df.head())

# ============================================
# 16. OVERALL KPIs
# ============================================

total_shipments = len(df)

total_sales = df["Sales"].sum()

gross_profit = df["Gross Profit"].sum()

gross_margin = (
    gross_profit / total_sales * 100
    if total_sales != 0 else 0
)

average_lead_time = df["Shipping Lead Time"].mean()

median_lead_time = df["Shipping Lead Time"].median()

total_routes = df["Route"].nunique()

delayed_shipments = (
    df["Delay Flag"] == "Delayed"
).sum()

delay_percentage = (
    delayed_shipments / total_shipments * 100
)

print("========== OVERALL KPIs ==========")
print("Total Shipments:", total_shipments)
print("Total Sales: $", round(total_sales, 2))
print("Gross Profit: $", round(gross_profit, 2))
print("Gross Margin: ", round(gross_margin, 2), "%")
print("Average Recorded Lead Time:",
      round(average_lead_time, 2), "days")
print("Median Recorded Lead Time:",
      round(median_lead_time, 2), "days")
print("Total Routes:", total_routes)
print("Provisional Delay %:",
      round(delay_percentage, 2), "%")

# ============================================
# 17. FACTORY ANALYSIS
# ============================================

factory_analysis = (
    df.groupby("Factory")
    .agg(
        Shipments=("Order ID", "count"),
        Average_Lead_Time=("Shipping Lead Time", "mean"),
        Median_Lead_Time=("Shipping Lead Time", "median"),
        Sales=("Sales", "sum"),
        Gross_Profit=("Gross Profit", "sum"),
        Units=("Units", "sum")
    )
    .reset_index()
)

factory_analysis["Gross Margin %"] = (
    factory_analysis["Gross_Profit"]
    / factory_analysis["Sales"]
    * 100
)

factory_analysis = factory_analysis.sort_values(
    "Shipments",
    ascending=False
)

display(factory_analysis)

# ============================================
# 18. FACTORY SHIPMENT CHART
# ============================================

plt.figure(figsize=(10, 6))

sns.barplot(
    data=factory_analysis,
    x="Shipments",
    y="Factory"
)

plt.title("Shipments by Factory")
plt.xlabel("Number of Shipments")
plt.ylabel("Factory")

plt.tight_layout()
plt.show()

# ============================================
# 19. SHIP MODE ANALYSIS
# ============================================

ship_mode_analysis = (
    df.groupby("Ship Mode")
    .agg(
        Shipments=("Order ID", "count"),
        Average_Lead_Time=("Shipping Lead Time", "mean"),
        Median_Lead_Time=("Shipping Lead Time", "median"),
        Sales=("Sales", "sum"),
        Units=("Units", "sum")
    )
    .reset_index()
)

display(ship_mode_analysis)

# ============================================
# 20. SHIP MODE CHART
# ============================================

plt.figure(figsize=(9, 6))

sns.barplot(
    data=ship_mode_analysis,
    x="Ship Mode",
    y="Shipments"
)

plt.title("Shipment Volume by Ship Mode")
plt.xlabel("Ship Mode")
plt.ylabel("Shipments")

plt.xticks(rotation=20)

plt.tight_layout()
plt.show()

# ============================================
# 21. REGION ANALYSIS
# ============================================

region_analysis = (
    df.groupby("Region")
    .agg(
        Shipments=("Order ID", "count"),
        Average_Lead_Time=("Shipping Lead Time", "mean"),
        Sales=("Sales", "sum"),
        Gross_Profit=("Gross Profit", "sum"),
        Units=("Units", "sum")
    )
    .reset_index()
)

display(region_analysis)

# ============================================
# 22. REGION SHIPMENT CHART
# ============================================

plt.figure(figsize=(9, 6))

sns.barplot(
    data=region_analysis,
    x="Region",
    y="Shipments"
)

plt.title("Shipments by Region")
plt.xlabel("Region")
plt.ylabel("Shipments")

plt.tight_layout()
plt.show()

# ============================================
# 23. STATE ANALYSIS
# ============================================

state_analysis = (
    df.groupby(
        ["State/Province", "Region"],
        dropna=False
    )
    .agg(
        Shipments=("Order ID", "count"),
        Average_Lead_Time=("Shipping Lead Time", "mean"),
        Median_Lead_Time=("Shipping Lead Time", "median"),
        Sales=("Sales", "sum"),
        Gross_Profit=("Gross Profit", "sum")
    )
    .reset_index()
)

state_analysis = state_analysis.sort_values(
    "Shipments",
    ascending=False
)

display(state_analysis.head(20))

# ============================================
# 24. TOP 10 STATES
# ============================================

top_states = state_analysis.head(10)

plt.figure(figsize=(10, 6))

sns.barplot(
    data=top_states,
    x="Shipments",
    y="State/Province"
)

plt.title("Top 10 States by Shipment Volume")
plt.xlabel("Shipments")
plt.ylabel("State")

plt.tight_layout()
plt.show()

# ============================================
# 25. ROUTE ANALYSIS
# ============================================

route_analysis = (
    df.groupby(
        ["Route", "Factory", "State/Province"],
        dropna=False
    )
    .agg(
        Total_Shipments=("Order ID", "count"),
        Average_Lead_Time=("Shipping Lead Time", "mean"),
        Median_Lead_Time=("Shipping Lead Time", "median"),
        Lead_Time_Std_Dev=("Shipping Lead Time", "std"),
        Total_Sales=("Sales", "sum"),
        Gross_Profit=("Gross Profit", "sum"),
        Total_Units=("Units", "sum")
    )
    .reset_index()
)

route_analysis["Lead_Time_Std_Dev"] = (
    route_analysis["Lead_Time_Std_Dev"].fillna(0)
)

display(route_analysis.head(20))

# ============================================
# 26. TOP ROUTES BY VOLUME
# ============================================

top_routes = route_analysis.sort_values(
    "Total_Shipments",
    ascending=False
).head(10)

display(top_routes)

plt.figure(figsize=(12, 7))

sns.barplot(
    data=top_routes,
    x="Total_Shipments",
    y="Route"
)

plt.title("Top 10 Factory-to-Customer Routes by Volume")
plt.xlabel("Shipments")
plt.ylabel("Route")

plt.tight_layout()
plt.show()

# ============================================
# 27. ROUTE EFFICIENCY SCORE
# ============================================

min_lead = route_analysis["Average_Lead_Time"].min()
max_lead = route_analysis["Average_Lead_Time"].max()

if max_lead != min_lead:
    route_analysis["Efficiency Score"] = (
        100 *
        (max_lead - route_analysis["Average_Lead_Time"])
        / (max_lead - min_lead)
    )
else:
    route_analysis["Efficiency Score"] = 100

display(
    route_analysis.sort_values(
        "Efficiency Score",
        ascending=False
    ).head(10)
)

# ============================================
# 28. LOWEST RECORDED LEAD-TIME ROUTES
# ============================================

efficient_routes = (
    route_analysis[
        route_analysis["Total_Shipments"] >= 10
    ]
    .sort_values(
        "Average_Lead_Time",
        ascending=True
    )
    .head(10)
)

display(efficient_routes)

# ============================================
# 29. HIGHEST RECORDED LEAD-TIME ROUTES
# ============================================

inefficient_routes = (
    route_analysis[
        route_analysis["Total_Shipments"] >= 10
    ]
    .sort_values(
        "Average_Lead_Time",
        ascending=False
    )
    .head(10)
)

display(inefficient_routes)

# ============================================
# 30. STATE SHIPMENT HEATMAP
# ============================================

fig = px.choropleth(
    state_analysis,
    locations="State/Province",
    locationmode="USA-states",
    color="Shipments",
    scope="usa",
    title="Nassau Candy Shipment Volume by State",
    color_continuous_scale="Blues"
)

fig.show()

# ============================================
# 31. SALES VS GROSS PROFIT BY REGION
# ============================================

fig = px.bar(
    region_analysis,
    x="Region",
    y=["Sales", "Gross_Profit"],
    barmode="group",
    title="Sales vs Gross Profit by Region"
)

fig.show()

# ============================================
# 32. MONTHLY SHIPMENT TREND
# ============================================

monthly_analysis = (
    df.groupby("Order Month")
    .agg(
        Shipments=("Order ID", "count"),
        Sales=("Sales", "sum")
    )
    .reset_index()
)

display(monthly_analysis)

fig = px.line(
    monthly_analysis,
    x="Order Month",
    y="Shipments",
    markers=True,
    title="Monthly Shipment Volume"
)

fig.show()

# ============================================
# 33. FACTORY-REGION ANALYSIS
# ============================================

factory_region = (
    df.groupby(
        ["Factory", "Region"]
    )
    .agg(
        Shipments=("Order ID", "count"),
        Average_Lead_Time=("Shipping Lead Time", "mean"),
        Sales=("Sales", "sum")
    )
    .reset_index()
)

display(
    factory_region.sort_values(
        "Shipments",
        ascending=False
    )
)

# ============================================
# 34. GEOGRAPHIC BOTTLENECK ANALYSIS
# ============================================

bottlenecks = state_analysis[
    state_analysis["Shipments"] >= 10
].copy()

bottlenecks["Shipment_Rank"] = (
    bottlenecks["Shipments"]
    .rank(ascending=False)
)

bottlenecks["Lead_Time_Rank"] = (
    bottlenecks["Average_Lead_Time"]
    .rank(ascending=False)
)

bottlenecks["Bottleneck_Index"] = (
    bottlenecks["Shipment_Rank"]
    + bottlenecks["Lead_Time_Rank"]
)

bottlenecks = bottlenecks.sort_values(
    "Bottleneck_Index"
)

display(bottlenecks.head(15))

# ============================================
# 35. DATA QUALITY SUMMARY
# ============================================

quality_summary = (
    df["Data Quality Status"]
    .value_counts()
    .reset_index()
)

quality_summary.columns = [
    "Status",
    "Records"
]

quality_summary["Percentage"] = (
    quality_summary["Records"]
    / len(df)
    * 100
)

display(quality_summary)

# ============================================
# 36. FINAL KPI TABLE
# ============================================

kpi_table = pd.DataFrame({
    "KPI": [
        "Total Shipments",
        "Total Sales",
        "Gross Profit",
        "Gross Margin %",
        "Average Recorded Lead Time",
        "Median Recorded Lead Time",
        "Total Routes",
        "Delayed Shipments - Provisional",
        "Delay % - Provisional"
    ],

    "Value": [
        total_shipments,
        round(total_sales, 2),
        round(gross_profit, 2),
        round(gross_margin, 2),
        round(average_lead_time, 2),
        round(median_lead_time, 2),
        total_routes,
        delayed_shipments,
        round(delay_percentage, 2)
    ]
})

display(kpi_table)

# ============================================
# 37. EXPORT CLEANED DATA
# ============================================

output_file = "/content/Nassau_Candy_Cleaned_Python.csv"

df.to_csv(
    output_file,
    index=False
)

print("Saved:", output_file)

# ============================================
# 38. EXPORT ANALYSIS TO EXCEL
# ============================================

excel_output = "/content/Nassau_Candy_Python_Analysis.xlsx"

with pd.ExcelWriter(
    excel_output,
    engine="openpyxl"
) as writer:

    df.to_excel(
        writer,
        sheet_name="Cleaned_Data",
        index=False
    )

    kpi_table.to_excel(
        writer,
        sheet_name="KPI_Summary",
        index=False
    )

    factory_analysis.to_excel(
        writer,
        sheet_name="Factory_Analysis",
        index=False
    )

    ship_mode_analysis.to_excel(
        writer,
        sheet_name="Ship_Mode",
        index=False
    )

    region_analysis.to_excel(
        writer,
        sheet_name="Region_Analysis",
        index=False
    )

    state_analysis.to_excel(
        writer,
        sheet_name="State_Analysis",
        index=False
    )

    route_analysis.to_excel(
        writer,
        sheet_name="Route_Analysis",
        index=False
    )

    quality_summary.to_excel(
        writer,
        sheet_name="Data_Quality",
        index=False
    )

print("Excel analysis file created!")

from google.colab import files

files.download(
    "/content/Nassau_Candy_Cleaned_Python.csv"
)

files.download(
    "/content/Nassau_Candy_Python_Analysis.xlsx"
)